# Generated by Django 3.1.6 on 2021-02-27 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('risk_profile', models.CharField(choices=[('CS', 'conservative'), ('MT', 'moderate'), ('DG', 'dashing')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(max_length=8)),
                ('trading_value', models.FloatField()),
                ('number_shares', models.IntegerField()),
                ('unit_share_price', models.FloatField()),
                ('tax', models.FloatField()),
                ('amout', models.FloatField()),
                ('operation_type', models.CharField(choices=[('PS', 'purchase'), ('SL', 'sale')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.investor')),
            ],
        ),
    ]
