# Generated by Django 3.1.6 on 2021-02-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='amout',
            new_name='amount',
        ),
    ]
